plugins {
	id 'fabric-loom' version '1.13-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

loom {
	accessWidenerPath = file("src/main/resources/vulkanmod.accesswidener")
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	ext.includeModule = { name ->
		var module = fabricApi.module(name, project.fabric_version)
		modImplementation(module)
		include(module)
	}

	includeModule("fabric-api-base")
	includeModule("fabric-resource-loader-v0")
	includeModule("fabric-resource-loader-v1")
	includeModule("fabric-rendering-v1")
	includeModule("fabric-renderer-api-v1")
	includeModule("fabric-rendering-fluids-v1")
	includeModule("fabric-block-view-api-v2")
	includeModule("fabric-lifecycle-events-v1")
	includeModule("fabric-transitive-access-wideners-v1")
}

project.ext.lwjglVersion = "3.3.3"
project.ext.jomlVersion = "1.10.4"

dependencies {
	// Vulkan — sem natives, Android usa libvulkan.so do sistema
	include(implementation("org.lwjgl:lwjgl-vulkan:$lwjglVersion"))

	// VMA e Shaderc — só o jar base, sem natives de nenhuma plataforma
	include(implementation("org.lwjgl:lwjgl-vma:$lwjglVersion"))
	include(implementation("org.lwjgl:lwjgl-shaderc:$lwjglVersion"))
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {}
}
